buildscript {
    repositories {
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
            }
        }
        maven { url = 'https://repo.grails.org/grails/restricted' }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
        classpath 'org.apache.grails.gradle:grails-publish'
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
            }
        }
        maven { url = 'https://repo.grails.org/grails/restricted' }
//      mavenLocal() // for local testing, do not commit uncommented
    }
}

version projectVersion
group "org.apache.grails"

subprojects { subproject ->
    subproject.version = rootProject.version
    subproject.group = rootProject.group

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    tasks.matching { it.name == "integrationTest" && it instanceof Test }.configureEach {
        shouldRunAfter tasks.test
        useJUnitPlatform()
    }

    if (subproject.name == 'cache-headers') {
        apply plugin: "org.apache.grails.gradle.grails-publish"
        grailsPublish {
            githubSlug = 'grails-plugins/cache-headers'
            license {
                name = 'Apache-2.0'
            }
            title = 'Grails Cache Headers Plugin'
            desc = 'Improve your application performance with browser caching, with easy ways to set caching headers\n' +
                    'in controller responses'
            developers = [sdelamo: 'Sergio del Amo', rahulshishodia: 'Rahul Shishodia']
        }
    }
}

