projectVersion=3.0.0
grailsVersion=7.0.5
gradleWrapperVersion=8.14.2
asciidoctorJvmVersion=4.0.4
customUserDataVersion=2.2.1
develocityVersion=4.0
websiteUrl=http://grails-plugins.github.io/cache-headers
issueTrackerUrl=https://github.com/grails-plugins/cache-headers/issues
vcsUrl=https://github.com/grails-plugins/cache-headers
bintrayUser=
bintrayKey=
grailsPortalUser=
grailsPortalPassword=
GRAILS_PUBLISH_RELEASE=false
