buildscript {
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/restricted" }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
        classpath "org.apache.grails:grails-data-hibernate5"
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'war'
}

apply plugin: "org.apache.grails.gradle.grails-web"
apply plugin: "org.apache.grails.gradle.grails-gson"

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

grails {
    plugins {
        implementation project(':cache-headers')
    }
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"

    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-codecs"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-datasource"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails:grails-async"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-views-gson"
    implementation "org.apache.grails:grails-data-mongodb-gson-templates"
    implementation "org.apache.grails:grails-cache"
    implementation "org.apache.grails:grails-data-hibernate5"
    implementation 'org.hibernate:hibernate-ehcache:5.6.15.Final'

    console "org.grails:grails-console"

    profile "org.grails.profiles:rest-api"
    runtimeOnly "com.h2database:h2"

    testImplementation "org.apache.grails:grails-testing-support-web"
    testImplementation "org.apache.grails:grails-testing-support-views-gson"
    testImplementation "org.apache.grails:grails-geb"
    testImplementation "org.seleniumhq.selenium:htmlunit-driver:4.13.0"
    testImplementation 'org.htmlunit:htmlunit:4.21.0'
}

apply from: "${rootDir}/gradle/integrationTestVerbose.gradle"
apply from: "${rootDir}/gradle/testVerbose.gradle"

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    sourceResources sourceSets.main
}
